config/routes.rb
Rails.application.routes.draw do

  root "posts#index", as: "home"

  get "about" => "pages#about", :as => "about"
  
  get "registration" => "users#new", as: "registration"
  post "users" => "users#create"

  resources :articles do
    resources :article_comments
  end

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_comments

  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_rich_text :body
  validates :title, presence: true, length: {minimum: 5}, uniqueness: true
  validates :body, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger
end

app/controllers/article_comments_controller.rb
class ArticleCommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.article_comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:article_comment).permit(:commenter, :body)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # http_basic_authenticate_with name: "admin", password: "123"
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comments_params)
    redirect_to post_path(@post)
  end

  private

  def comments_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = "Страничка про нас"
    @text = "Просто текст"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # http_basic_authenticate_with name: "admin", password: "123", except: [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, success: "Пост обновлён"
    else
      render :edit, danger: "Пост не обновлён"
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: "Пост удалён"
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: "Пост создан"
    else
      render :new, danger: "Пост не создан"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password))
    if @user.save
      redirect_to home_path
    else
      redirect_to :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/article_comments/_article_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= article_comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= article_comment.body %>
</p>

app/views/article_comments/_form.html.erb
<%= form_with model: [ @article, @article.article_comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <%= article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <%= article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>
<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <%= @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <%= @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.article_comments %>

<h2>Add a comment:</h2>
<%= render 'article_comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRailsSandbox</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <%= link_to image_tag('logo.png', width: 100), home_path, class: "my-0 mr-md-auto" %>
  <nav class="my-2 my-md-0 mr-md-3">
    <span class="p-2 text-dark"><%= link_to "Про нас", about_path %></span>
  </nav>
  <span class="p-2 text-dark"><%= link_to "Добавление статьи", new_post_path %></span>
  <span class="p-2 text-dark"><%= link_to "Регистрация", registration_path %></span>
</div>
<div class="container">
  <div class="row">
    <% flash.each do |name, mes| %>
    <div class="alert alert-<%= name %>">
      <%= mes %>
    </div>
    <% end %>
  </div>
</div>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h4><%= @heading %></h4>
<p><%= @text %></p>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <div class="alert alert-light">
      <small>
        <time>
          <%=post.created_at.to_date.strftime("%d, %B, %Y") %>
        </time>
      </small>
      <h3><%= post.title %></h3>
      <p><%= post.body %></p>
      <%= link_to "Читать далее..", post_path(post), class: 'btn btn-outline-success' %>
      <%= link_to "Изменить", edit_post_path(post), class: 'btn btn-outline-info' %>
      <%= link_to "Удалить", post_path(post), method: :delete, data: {confirm: "Хотите удалить статью?"}, class: 'btn btn-outline-danger'  %>
    </div>
  </section>
</article>

app/views/posts/edit.html.erb
<h2>Редактирование поста</h2>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <p>Название
    <%= f.text_field(:title, {class: 'form-control'}) %>
  </p>
  <p>Тескт статьи
    <%= f.rich_text_area(:body, {class: 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({class: 'btn btn-success'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Все посты</h1>
<%= render @post %>

app/views/posts/new.html.erb
<h2>Добавление нового поста</h2>

<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

  <p>Название
    <%= f.text_field(:title, {class: 'form-control'}) %>
  </p>
  <p>Тескт статьи
    <%= f.rich_text_area(:body, {class: 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({class: 'btn btn-success'}) %>
    <%= link_to "Назад", :back, ({class: 'btn btn-outline-success'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title  %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), class: 'btn btn-warning' %>
<%= link_to "Удалить пост", post_path(@post), method: :delete, data: {confirm: "Хотите удалить статью?"}, class: 'btn btn-danger' %>
<hr>
<h1>Все комментарии</h1>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p>
      <strong><%= comment.username %></strong>: <%= comment.body %>
    </p>
  </div>
<% end %>
<hr>
<h2> Добавление комментария</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>Пользователь
    <%= f.text_field(:username, {class: 'form-control'}) %>
  </p>
  <p>Тескт комментария
    <%= f.text_area(:body, {class: 'form-control'}) %>
  </p>
  <p>
    <%= f.submit("Добавить комментарий", {class: 'btn btn-warning'}) %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Регистрация</h1>
<%= form_for(@user) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password%>
  </div>
  <div>
    <%= form.submit "Зарегиться" %>
  </div>
<% end %>